### ISSUE TITLE
localizations

### ISSUE THREAD

**Issue by Elderly-Emre** [Deaadman/ItemRarities#1]
Can you add the localizations file?

**Comment by Elderly-Emre** [comment]
I am adding the Turkish equivalents

Common       -  Yaygın
Uncommon   -  Sıradışı
Rare               -  Nadir
Epic                - Destansı
Legendary     - Efsanevi
Mythic           - Mitik

**Comment by Deaadman** [comment]
Yes, I can I'll do this as soon as possible and close this issue once it's done.

Thank you for your help, it is greatly appreciated!

**Comment by Elderly-Emre** [comment]
You are very understanding. I am grateful to you

**Comment by Deaadman** [comment]
The issue should now be resolved in this new [**pre-release**](https://github.com/Deaadman/ItemRarities/releases/tag/v1.1.0-rc.0).

If there are any issues, don't be afraid to open another issue thread or tell me underneath my channel in the [**TLD modding discord server**](https://discord.gg/2mnXAZfGXQ).

And if you have any other translations, I would be more than happy to add them for you!

Thanks for the feedback!
