### ISSUE TITLE
Modded Items Have No Label on Hover

### ISSUE THREAD

**Issue by saddamonpc** [Deaadman/ItemRarities#10]
### The Long Dark Version
v 2.31

### Mod Version
v 2.0.0

### Other Mods Installed
AlcoholMod v2.0.4
AmbientLights v2.8.1
AuroraMonitor v1.0.0
Candlelight v1.8.2
Clothing Expanded v1.0.3
ComplexLogger v1.0.5
CraftingRevisions v2.3.2
DeveloperConsole v1.7.0
DIY by Santana v2.2
ExtraGraphicsSettings v1.1.4
Food Pack by TKG v5.5
FoodsByCalorieWaltz v1.0.7
FullSwing v1.0.0
GearSpawner v2.3.2
Modders' Gear Toolbox v1.0.3
HouseLights v2.5.2
ImprovedLoadingScreens v1.2.1
KeyboardUtilities v2.0.0
LocalizationUtilities v2.0.0
MapManager v1.1.6
ModComponent v6.3.1
ModData v1.5.3
ModSettings v2.0.0
PlacingAnywhere v2.6.0
QoL v1.6.3
RandomMainMenu v2.2.0
RetroFood v1.3
RunInBackground v1.2.0
SkipIntroRedux v3.1.1
TimeAccelerator v3.0.0
TinyTweaks-FixDroppedOrientation v1.1.0
TinyTweaks-MapTextOuline v1.1.0
Universal Tweaks v1.4.2
UseTheWorstFirstAndDropStone v1.0.0

### Describe the Issue
Modded items on the ground / that can be picked up have no label when the crosshair hovers over them. I suspect that this happens because modded items have no rarities compared to vanilla items. I expected that modded items have a default label color, such as white on hover.

I noticed that the label's width change sizes on different items, suggesting that the item's name does show up, but it is transparent.

### Steps to Reproduce
Just use any modded items (such as Candlelight, Food Pack, etc.) and said issues will show up.

### Log Output
[Latest.log](https://github.com/user-attachments/files/16216477/Latest.log)

### Screenshots
![screen_(-3, 2, 0)_f6754fb0-853c-4a4c-9f34-fadc0e9c5a83](https://github.com/user-attachments/assets/43398f77-555f-4c94-ab38-1487e8b74e06)
![screen_(-3, 2, 0)_6832c6a1-9497-4605-8243-a566d566d44b](https://github.com/user-attachments/assets/3daad732-3a55-4ccd-9f5a-58b00823bc21)

**Comment by Deaadman** [comment]
Thank you for this report, it seems there were quite a few issues then initially thought before release. So I'm terribly sorry that you have had to experience all these.

But this issue in particular I have already found, and fixed - it'll be in the next **2.0.1** update. You can see a list of the bugs that I have found in what has been fixed in the **[trello](https://trello.com/b/8iayqOyj/item-rarities)** board.

**Comment by Deaadman** [comment]
This issue should now be fixed in **[2.0.1](https://github.com/Deaadman/ItemRarities/releases/tag/v2.0.1)**.
