### ISSUE TITLE
Modded Items Have No Grid Colour in Inventory

### ISSUE THREAD

**Issue by saddamonpc** [Deaadman/ItemRarities#11]
### The Long Dark Version
v 2.3.1

### Mod Version
v 2.0.0

### Other Mods Installed
AlcoholMod v2.0.4
AmbientLights v2.8.1
AuroraMonitor v1.0.0
Candlelight v1.8.2
Clothing Expanded v1.0.3
ComplexLogger v1.0.5
CraftingRevisions v2.3.2
DeveloperConsole v1.7.0
DIY by Santana v2.2
ExtraGraphicsSettings v1.1.4
Food Pack by TKG v5.5
FoodsByCalorieWaltz v1.0.7
FullSwing v1.0.0
GearSpawner v2.3.2
Modders' Gear Toolbox v1.0.3
HouseLights v2.5.2
ImprovedLoadingScreens v1.2.1
KeyboardUtilities v2.0.0
LocalizationUtilities v2.0.0
MapManager v1.1.6
ModComponent v6.3.1
ModData v1.5.3
ModSettings v2.0.0
PlacingAnywhere v2.6.0
QoL v1.6.3
RandomMainMenu v2.2.0
RetroFood v1.3
RunInBackground v1.2.0
SkipIntroRedux v3.1.1
TimeAccelerator v3.0.0
TinyTweaks-FixDroppedOrientation v1.1.0
TinyTweaks-MapTextOuline v1.1.0
Universal Tweaks v1.4.2
UseTheWorstFirstAndDropStone v1.0.0

### Describe the Issue
Modded items in the inventory (backpack) have no grid colour, making it hard for me to see where is my current selection. I expected that items have a default grid colour, such as white on selection.

### Steps to Reproduce
Just use any modded items (such as Candlelight, Food Pack, etc.) and said issues will show up.

### Log Output
[Latest.log](https://github.com/user-attachments/files/16216486/Latest.log)

### Screenshots
![screen_(7, 1, 8)_9adccdd5-bd13-4b46-8ae2-be28154d4040](https://github.com/user-attachments/assets/c66fe49c-338a-4ea0-b5b9-50634aa044fa)

**Comment by Deaadman** [comment]
Much like the other report, this issue I have discovered and already fixed - it'll be in the next **2.0.1** update as well.

**Comment by Deaadman** [comment]
This issue should now be fixed in **[2.0.1](https://github.com/Deaadman/ItemRarities/releases/tag/v2.0.1)**.
