### ISSUE TITLE
Modded Clothing Cannot Be Selected with Mouse Cursor Once Worn in the Clothing Menu

### ISSUE THREAD

**Issue by saddamonpc** [Deaadman/ItemRarities#12]
### The Long Dark Version
v 2.3.1

### Mod Version
v 2.0.0

### Other Mods Installed
AlcoholMod v2.0.4
AmbientLights v2.8.1
AuroraMonitor v1.0.0
Candlelight v1.8.2
Clothing Expanded v1.0.3
ComplexLogger v1.0.5
CraftingRevisions v2.3.2
DeveloperConsole v1.7.0
DIY by Santana v2.2
ExtraGraphicsSettings v1.1.4
Food Pack by TKG v5.5
FoodsByCalorieWaltz v1.0.7
FullSwing v1.0.0
GearSpawner v2.3.2
Modders' Gear Toolbox v1.0.3
HouseLights v2.5.2
ImprovedLoadingScreens v1.2.1
KeyboardUtilities v2.0.0
LocalizationUtilities v2.0.0
MapManager v1.1.6
ModComponent v6.3.1
ModData v1.5.3
ModSettings v2.0.0
PlacingAnywhere v2.6.0
QoL v1.6.3
RandomMainMenu v2.2.0
RetroFood v1.3
RunInBackground v1.2.0
SkipIntroRedux v3.1.1
TimeAccelerator v3.0.0
TinyTweaks-FixDroppedOrientation v1.1.0
TinyTweaks-MapTextOuline v1.1.0
Universal Tweaks v1.4.2
UseTheWorstFirstAndDropStone v1.0.0

### Describe the Issue
Modded clothing once worn, cannot be selected in the clothing menu with the mouse cursor. Left clicking the worn modded clothing in the clothing grid will not do anything. Thankfully, the clothing can still be selected via WASD keys (QoL mod) or removed by choosing drop in the inventory menu.

Notice that issue #11 also occur here (see screenshot, no grid colour on selection).

### Steps to Reproduce
Use any clothing mod (such as Clothing Expanded), go to clothing menu, wear a clothing from the clothing mod, select any other vanilla clothing in the current menu, and said issue will show up.

### Screenshots
![screen_(7, 1, 8)_41e7f6ad-f776-49cc-a372-cd48fb6d088d](https://github.com/user-attachments/assets/9b3284fd-f31c-440a-bf00-ff282424a300)
![screen_(7, 1, 8)_365b963b-f4d7-48a3-9307-c5b4bafa6215](https://github.com/user-attachments/assets/f7843ea2-bd55-4dc6-ae36-8d67cd03bfc6)

**Comment by saddamonpc** [comment]
Oh and sorry, forgot to attach the log output.
[Latest.log](https://github.com/user-attachments/files/16216533/Latest.log)

**Comment by Deaadman** [comment]
Unlike the previous two issue, I haven't actually come across this one myself - and that's probably due to the fact that I don't play with modded clothing, so I really appreciate this report. I added it to the **[trello](https://trello.com/b/8iayqOyj/item-rarities)** board, and I'll do some investigating when I get the time. So thank you for this report :)

**Comment by saddamonpc** [comment]
That's great! But, I tried to access the trello board, and it says that the board itself is private - I can't access it, even with an account.

**Comment by Deaadman** [comment]
Are you able to access it now?

**Comment by saddamonpc** [comment]
Yes. No problem accessing it now.

**Comment by Deaadman** [comment]
This issue should now be fixed in **[2.0.1](https://github.com/Deaadman/ItemRarities/releases/tag/v2.0.1)**.
