### ISSUE TITLE
Russian Localisation

### ISSUE THREAD

**Issue by Lev234** [Deaadman/ItemRarities#14]
### Describe the Feature

Can you add russian localisation?

Common - Обычное
Uncommon - Необычное
Rare - Редкое
Epic - Эпичное
Legendary - Легендарное
Mythic - Мифическое

### Benefit of the Feature

ю

**Comment by Deaadman** [comment]
Yes, I will add these translations as soon as I can. Thank you for contributing!

**Comment by Deaadman** [comment]
The Russian language is now supported in [v2.0.3](https://github.com/Deaadman/ItemRarities/releases/tag/v2.0.3)!

Thank you for your contribution :)
