### ISSUE TITLE
Italian Localization

### ISSUE THREAD

**Issue by LettereUniche** [Deaadman/ItemRarities#3]
Hello,
I'll leave all the italian traslantions for this mod.

common = comune
uncommon = non comune
rare = raro
epic = epico
legendary = leggendario
mythical = mitico

**Comment by Deaadman** [comment]
The issue should now be resolved in the latest [**release**](https://github.com/Deaadman/ItemRarities/releases/latest) of ItemRarities.

Thank you for providing the translations for this mod, not only are you helping me - but you are helping many others!
